"""Build script.json for Ink & Testimony E02 — 'The Examination Table'.

Generates the canonical `script` artifact from authored beat content: computes
start/end timestamps from word count at a contemplative-conversational pace
with fixed inter-beat gaps (matching the E01-validated pause_policy), and
auto-derives provider_text number-spelling where not explicitly overridden.
"""
import json

WPS = 2.35          # words per second, contemplative-conversational (matches E01 density)
GAP = 0.55           # inter-beat gap, validated E01 pause_policy
CARD_DURATION = 3.2  # act-break title card: read time
CARD_GAP = 0.8        # slightly longer dwell after a card

# Each entry: (id, label, text, provider_text, pace, energy, emphasis, enhancement_type,
#              enhancement_desc, pronun[list of (word,phon)], source_ref, is_card)
BEATS = [
    ("s1", "Cold Open — The Table",
     "Every tiger in this story was cut open after it died.",
     "Every tiger in this story was cut open after it died.",
     "measured", "low", [], "overlay",
     "Ink frame: an examination/postmortem table, instruments laid beside a tiger's still form, seen from the head end. Full-bleed, no border.",
     [], "concept C1 framing device", False),
    ("s2", "Cold Open — Not Trophy",
     "Not for trophy. For evidence — because someone always asked the same question.",
     "Not for trophy. For evidence -- because someone always asked the same question.",
     "measured", "low", ["evidence"], None, None, [], "concept C1 framing device", False),
    ("s3", "Cold Open — The Question",
     "Why did this one decide people were prey?",
     "Why did this one decide people were prey?",
     "slow", "low", ["prey"], None, None, [], "concept C1 framing device", False),

    ("c1", "ACT ONE title card", "ACT ONE — VERMIN", "Act One. Vermin.",
     "measured", "low", [], "overlay", "ffmpeg drawtext act-break title card on a plain ink-paper background; NOT AI-generated text, no image generation for this beat.",
     [], "act structure", True),

    ("s4", "A Century Before",
     "The answer starts almost a hundred years before anyone asked it about a man-eater by name.",
     "The answer starts almost a hundred years before anyone asked it about a man-eater by name.",
     "measured", "low", [], "broll", "Ink frame: a colonial-era district office, ledgers on a desk, seen through a doorway.", [],
     "research_brief.data_points (bounty system context)", False),
    ("s5", "1822",
     "In 1822, the East India Company began paying for dead tigers.",
     "In eighteen twenty-two, the East India Company began paying for dead tigers.",
     "measured", "low", ["1822"], None, None, [], "research_brief.data_points (East India Company bounty data point)", False),
    ("s6", "Ten Rupees",
     "Ten rupees a head, in the Bengal Presidency alone.",
     "Ten rupees a head, in the Bengal Presidency alone.",
     "measured", "low", [], "stat_card", "Overlay text: '10 rupees per tiger — Bengal Presidency, 1822'", [],
     "research_brief.data_points (East India Company bounty data point)", False),
    ("s7", "Vermin",
     "On paper, the tiger stopped being a predator. It became vermin — a pest to be cleared, like weeds from a field.",
     "On paper, the tiger stopped being a predator. It became vermin -- a pest to be cleared, like weeds from a field.",
     "measured", "low", ["vermin"], None, None, [], "research_brief.sources (ThePrint bounty excerpt)", False),
    ("s8", "The Bounty Spreads",
     "The bounty spread, province by province, for the rest of the century.",
     "The bounty spread, province by province, for the rest of the century.",
     "conversational", "low", [], None, None, [], "research_brief.sources (ThePrint bounty excerpt)", False),
    ("s9", "Four Months' Pay",
     "In some districts, a single tiger's head was worth four months of a court officer's pay.",
     "In some districts, a single tiger's head was worth four months of a court officer's pay.",
     "measured", "low", [], "broll", "Ink frame: a stack of rupee notes and a tiger-claw trophy on a district officer's desk.", [],
     "research_brief.sources (ThePrint bounty excerpt)", False),
    ("s10", "16,573 Tigers",
     "Between 1879 and 1888 alone, the scheme paid out for 16,573 tigers.",
     "Between eighteen seventy-nine and eighteen eighty-eight alone, the scheme paid out for sixteen thousand, five hundred and seventy-three tigers.",
     "measured", "low", ["16,573"], "stat_card", "Overlay text: '16,573 tigers killed under the bounty system, 1879-1888'", [],
     "research_brief.data_points (East India Company bounty data point)", False),
    ("s11", "The Forests",
     "At the same time, the forests those tigers depended on were being taken apart.",
     "At the same time, the forests those tigers depended on were being taken apart.",
     "measured", "low", [], "broll", "Ink frame: felled timber stacked beside a half-cleared forest edge.", [],
     "research_brief.landscape (Forest Acts finding)", False),
    ("s12", "Forest Acts",
     "The Forest Acts of 1865 and 1878 gave the state control of the woodland — and took hunting rights away from the villagers who actually lived in it.",
     "The Forest Acts of eighteen sixty-five and eighteen seventy-eight gave the state control of the woodland -- and took hunting rights away from the villagers who actually lived in it.",
     "measured", "low", ["1865", "1878"], None, None, [],
     "research_brief.sources (science.thewire.in colonial forestry critique)", False),
    ("s13", "The Sundarbans",
     "In the Sundarbans, the tidal forest where the Ganges meets the sea, landlords sent clearing gangs in to turn mangrove swamp into farmland.",
     "In the Sundarbans, the tidal forest where the Ganges meets the sea, landlords sent clearing gangs in to turn mangrove swamp into farmland.",
     "measured", "low", [], "broll", "Ink frame: a narrow tidal creek through dense mangrove, a small boat and clearing tools at the bank.",
     [("Sundarbans", "SUN-dar-bans")], "research_brief.landscape (Sundarbans colonization)", False),
    ("s14", "Already There",
     "The tigers were already there.",
     "The tigers were already there.",
     "slow", "low", ["already"], None, None, [], "research_brief.landscape (Sundarbans colonization)", False),
    ("s15", "4,200 Deaths",
     "Colonial records from the 1860s count more than 4,200 deaths across just six years, in that one stretch of forest.",
     "Colonial records from the eighteen sixties count more than four thousand two hundred deaths across just six years, in that one stretch of forest.",
     "slow", "low", ["4,200"], "stat_card", "Overlay text: '4,218 deaths in six years — Sundarbans, 1860s (colonial-era records)'", [],
     "research_brief.data_points (Sundarbans colonial-era death-toll data point)", False),
    ("s16", "Seven Hundred a Year",
     "Seven hundred people a year. Killed by tigers. In a single delta.",
     "Seven hundred people a year. Killed by tigers. In a single delta.",
     "slow", "low", ["seven hundred"], None, None, [],
     "research_brief.data_points (Sundarbans colonial-era death-toll data point)", False),
    ("s17", "A Tiger Problem",
     "The British called it a tiger problem.",
     "The British called it a tiger problem.",
     "measured", "low", [], None, None, [], "research_brief.landscape (underserved gap)", False),
    ("s18", "Also a Policy Problem",
     "It was also a forest problem, a policy problem, and a hunger problem — for tigers losing the ground they'd always hunted on.",
     "It was also a forest problem, a policy problem, and a hunger problem -- for tigers losing the ground they'd always hunted on.",
     "measured", "medium", ["also"], None, None, [],
     "research_brief.angles_discovered (The Colonial Machine That Made the Man-Eater)", False),

    ("c2", "ACT TWO title card", "ACT TWO — THE EXAMINATION", "Act Two. The Examination.",
     "measured", "low", [], "overlay", "ffmpeg drawtext act-break title card, plain ink-paper background; no image generation.",
     [], "act structure", True),

    ("s19", "The Last Years of the 1800s",
     "In the last years of the 1800s, a tigress began killing people in the hill forests of western Nepal.",
     "In the last years of the eighteen hundreds, a tigress began killing people in the hill forests of western Nepal.",
     "measured", "low", [], "broll", "Ink frame: dense hill forest at dusk, a narrow footpath vanishing into the treeline.", [],
     "research_brief.data_points (Champawat data point)", False),
    ("s20", "Methodically",
     "She wasn't hunting cattle. She wasn't hunting deer. She was hunting people, methodically, for years.",
     "She wasn't hunting cattle. She wasn't hunting deer. She was hunting people, methodically, for years.",
     "measured", "medium", ["methodically"], None, None, [], "research_brief.data_points (Champawat data point)", False),
    ("s21", "Driven Across the Border",
     "Nepalese authorities eventually drove her across the border into the Kumaon hills of British India.",
     "Nepalese authorities eventually drove her across the border into the Kumaon hills of British India.",
     "measured", "low", [], None, None, [("Kumaon", "koo-MOW-un")],
     "research_brief.data_points (Champawat data point)", False),
    ("s22", "She Didn't Stop",
     "She didn't stop.",
     "She didn't stop.",
     "slow", "low", [], None, None, [], "research_brief.data_points (Champawat data point)", False),
    ("s23", "436 People",
     "By 1907, her toll stood at an estimated 436 people — the highest ever recorded for a single animal.",
     "By nineteen oh seven, her toll stood at an estimated four hundred and thirty-six people -- the highest ever recorded for a single animal.",
     "slow", "low", ["436"], "stat_card", "Overlay text: 'An estimated 436 dead — the highest verified toll of any wild animal on record'",
     [("Champawat", "cham-PAH-wut")], "research_brief.data_points (Champawat 436-victim data point)", False),
    ("s24", "Women and Children",
     "Most of her victims were women and children, gathering firewood or grass, doing the ordinary work of a hill village.",
     "Most of her victims were women and children, gathering firewood or grass, doing the ordinary work of a hill village.",
     "slow", "low", [], "broll", "Ink frame: a woman's dropped sickle and a bundle of cut grass on a forest path, no figure present.", [],
     "research_brief.data_points (Champawat data point)", False),
    ("s25", "Jim Corbett",
     "The government finally called in a 31-year-old railway man and hunter named Jim Corbett.",
     "The government finally called in a thirty-one-year-old railway man and hunter named Jim Corbett.",
     "measured", "low", ["Corbett"], "broll", "Ink frame: a lean young man in field clothes, rifle broken open over his arm, seen from behind entering treeline.", [],
     "research_brief.data_points (Champawat data point)", False),
    ("s26", "First Man-Eater",
     "It was the first man-eater he was ever officially asked to kill.",
     "It was the first man-eater he was ever officially asked to kill.",
     "measured", "low", ["first"], None, None, [], "research_brief.data_points (Champawat data point)", False),
    ("s27", "Nearly 300 Villagers",
     "Corbett tracked her on foot, with a beat line of nearly 300 villagers driving the forest ahead of him.",
     "Corbett tracked her on foot, with a beat line of nearly three hundred villagers driving the forest ahead of him.",
     "measured", "medium", ["300"], "broll", "Ink frame: a long line of villagers with sticks and drums moving through undergrowth, seen from a high angle.", [],
     "research_brief.data_points (Champawat data point)", False),
    ("s28", "May 12, 1907",
     "On the 12th of May, 1907, he found her, and he killed her.",
     "On the twelfth of May, nineteen oh seven, he found her, and he killed her.",
     "measured", "medium", ["killed"], "stat_card", "Overlay text: '12 May 1907'", [],
     "research_brief.data_points (Champawat data point)", False),
    ("s29", "Something the Others Didn't Do",
     "Then he did something the bounty hunters before him rarely bothered with.",
     "Then he did something the bounty hunters before him rarely bothered with.",
     "measured", "low", [], None, None, [], "research_brief.angles_discovered (What the Post-Mortem Table Revealed)", False),
    ("s30", "He Looked",
     "He turned the body over and looked.",
     "He turned the body over and looked.",
     "slow", "low", ["looked"], "overlay", "Ink frame: close view of hands examining a tiger's jaw, on the examination table from the cold open.", [],
     "research_brief.angles_discovered (What the Post-Mortem Table Revealed)", False),
    ("s31", "The Broken Canine",
     "Her upper right canine was broken clean in half. The lower one was shattered to the gum.",
     "Her upper right canine was broken clean in half. The lower one was shattered to the gum.",
     "slow", "low", ["broken", "shattered"], "overlay", "White-ink-on-black inversion: close detail of a broken tiger canine tooth.", [],
     "research_brief.data_points (Champawat canine-injury data point)", False),
    ("s32", "An Old Gunshot Wound",
     "Old damage. Almost certainly an old gunshot wound, from some earlier, unrecorded encounter with a hunter.",
     "Old damage. Almost certainly an old gunshot wound, from some earlier, unrecorded encounter with a hunter.",
     "slow", "low", ["gunshot"], None, None, [], "research_brief.data_points (Champawat canine-injury data point)", False),
    ("s33", "Cannot Bring Down a Deer",
     "A tiger with a ruined jaw cannot bring down a deer, or a boar, or a buffalo.",
     "A tiger with a ruined jaw cannot bring down a deer, or a boar, or a buffalo.",
     "measured", "low", [], None, None, [], "research_brief.expert_voices (Corbett's compulsion thesis)", False),
    ("s34", "But It Can Catch a Woman",
     "It can still catch a woman bent over, cutting grass.",
     "It can still catch a woman bent over, cutting grass.",
     "slow", "low", ["still"], None, None, [], "research_brief.audience_insights.misconceptions (injury-causation myth)", False),

    ("c3", "ACT THREE title card", "ACT THREE — WHAT MADE HER", "Act Three. What Made Her.",
     "measured", "low", [], "overlay", "ffmpeg drawtext act-break title card, plain ink-paper background; no image generation.",
     [], "act structure", True),

    ("s35", "The First Hard Evidence",
     "That postmortem became the first hard evidence for something naturalists had only suspected.",
     "That postmortem became the first hard evidence for something naturalists had only suspected.",
     "measured", "low", [], None, None, [], "research_brief.expert_voices (Corbett's compulsion thesis)", False),
    ("s36", "Not Born",
     "Tigers are not born man-eaters.",
     "Tigers are not born man-eaters.",
     "slow", "low", ["not"], None, None, [], "research_brief.audience_insights.misconceptions (injury-causation myth)", False),
    ("s37", "The Pattern Repeats",
     "In case after documented case, the pattern repeats: an injury, an infection, a missing tooth — something that takes normal prey off the menu.",
     "In case after documented case, the pattern repeats: an injury, an infection, a missing tooth -- something that takes normal prey off the menu.",
     "measured", "medium", ["repeats"], "diagram", "Simple ink diagram motif: a line of tiger silhouettes, each marked with the same small wound icon.", [],
     "research_brief.data_points (modern science consensus on causes)", False),
    ("s38", "A Shrinking Forest",
     "Add in a shrinking forest, and fewer deer and boar to begin with, and an injured tiger has almost nowhere else to turn.",
     "Add in a shrinking forest, and fewer deer and boar to begin with, and an injured tiger has almost nowhere else to turn.",
     "measured", "low", [], None, None, [], "research_brief.data_points (prey depletion causation)", False),
    ("s39", "Slow, Unarmed",
     "Humans are slow. Unarmed. And, increasingly, standing in what used to be tiger ground.",
     "Humans are slow. Unarmed. And, increasingly, standing in what used to be tiger ground.",
     "measured", "medium", [], None, None, [], "research_brief.data_points (habitat loss causation)", False),
    ("s40", "Arithmetic",
     "It is not appetite. It's arithmetic.",
     "It is not appetite. It's arithmetic.",
     "slow", "low", ["arithmetic"], None, None, [], "research_brief.research_summary", False),
    ("s41", "22 Years Later",
     "22 years after Champawat, the pattern showed up again — twice at once.",
     "Twenty-two years after Champawat, the pattern showed up again -- twice at once.",
     "measured", "medium", ["twice"], None, None, [], "research_brief.data_points (Chowgarh 64-victim data point)", False),
    ("s42", "1925",
     "In 1925, an old tigress and her half-grown cub began killing across the Chowgarh hills of eastern Kumaon.",
     "In nineteen twenty-five, an old tigress and her half-grown cub began killing across the Chowgarh hills of eastern Kumaon.",
     "measured", "low", ["1925"], "broll", "Ink frame: two tiger tracks side by side in soft ground, one larger, one smaller.",
     [("Chowgarh", "CHOW-gur")], "research_brief.data_points (Chowgarh 64-victim data point)", False),
    ("s43", "64 People",
     "Over five years, hunting together and then separately, they killed a reported 64 people, across 1,500 square miles of mountain and forest.",
     "Over five years, hunting together and then separately, they killed a reported sixty-four people, across fifteen hundred square miles of mountain and forest.",
     "measured", "low", ["64"], "stat_card", "Overlay text: '64 dead — Chowgarh tigers, 1925-1930, across 1,500 square miles'", [],
     "research_brief.data_points (Chowgarh 64-victim data point)", False),
    ("s44", "Called Back",
     "Corbett was called back.",
     "Corbett was called back.",
     "measured", "low", [], None, None, [], "research_brief.data_points (Chowgarh 64-victim data point)", False),
    ("s45", "The Cub, 1929",
     "He killed the cub in 1929, tracking it while carrying a basket of bird eggs — his collection was missing that species, and he refused to leave the search without them.",
     "He killed the cub in nineteen twenty-nine, tracking it while carrying a basket of bird eggs -- his collection was missing that species, and he refused to leave the search without them.",
     "conversational", "medium", ["1929"], "broll", "Ink frame: a small wicker egg-basket set carefully on a rock beside a rifle.", [],
     "research_brief.data_points (Chowgarh case)", False),
    ("s46", "The Mother Took Longer",
     "The mother took another year.",
     "The mother took another year.",
     "measured", "low", [], None, None, [], "research_brief.data_points (Chowgarh case)", False),
    ("s47", "April 1930",
     "He finally killed her in April of 1930, on a hillside where villagers had stopped using the footpaths connecting their own homes.",
     "He finally killed her in April of nineteen thirty, on a hillside where villagers had stopped using the footpaths connecting their own homes.",
     "measured", "low", ["1930"], None, None, [], "research_brief.data_points (Chowgarh case)", False),
    ("s48", "Rearranged Lives",
     "In the years between, entire families had rearranged their lives around where the tigers had last been seen.",
     "In the years between, entire families had rearranged their lives around where the tigers had last been seen.",
     "measured", "low", [], "broll", "Ink frame: an empty village footpath overgrown at the edges, a longer cleared detour visible beside it.", [],
     "research_brief.data_points (Chowgarh case)", False),
    ("s49", "Not Just the Dead",
     "That is what a man-eater actually costs. Not just the dead.",
     "That is what a man-eater actually costs. Not just the dead.",
     "slow", "low", ["costs"], None, None, [], "research_brief.audience_insights.pain_points", False),
    ("s50", "Redrawing the Map",
     "It is the living, redrawing the map of where they're allowed to walk.",
     "It is the living, redrawing the map of where they're allowed to walk.",
     "slow", "low", ["redrawing"], None, None, [], "research_brief.audience_insights.pain_points", False),

    ("c4", "ACT FOUR title card", "ACT FOUR — THE LAST HUNT", "Act Four. The Last Hunt.",
     "measured", "low", [], "overlay", "ffmpeg drawtext act-break title card, plain ink-paper background; no image generation.",
     [], "act structure", True),

    ("s51", "No Longer Just a Hunter",
     "By the 1930s, Corbett was no longer just a hunter for hire.",
     "By the nineteen thirties, Corbett was no longer just a hunter for hire.",
     "measured", "low", [], None, None, [], "research_brief.expert_voices (Corbett legacy)", False),
    ("s52", "Arguing for Protection",
     "He'd started arguing, in print and in person, for something almost nobody in his position argued for: protecting the tigers that weren't killing anyone.",
     "He'd started arguing, in print and in person, for something almost nobody in his position argued for: protecting the tigers that weren't killing anyone.",
     "measured", "medium", ["protecting"], None, None, [], "research_brief.data_points (Corbett National Park founding data point)", False),
    ("s53", "1936",
     "In 1936, British India's first tiger reserve was established in the hills he knew best.",
     "In nineteen thirty-six, British India's first tiger reserve was established in the hills he knew best.",
     "measured", "medium", ["first"], "stat_card", "Overlay text: '1936 — India's first tiger reserve established'", [],
     "research_brief.data_points (Corbett National Park founding data point)", False),
    ("s54", "Thirty Years of Evidence",
     "He'd spent thirty years documenting exactly how a healthy tiger turns into a man-eater. Now he wanted to make sure fewer of them had to.",
     "He'd spent thirty years documenting exactly how a healthy tiger turns into a man-eater. Now he wanted to make sure fewer of them had to.",
     "measured", "low", [], None, None, [], "research_brief.data_points (Corbett National Park founding data point)", False),
    ("s55", "One More",
     "But the government asked him for one more.",
     "But the government asked him for one more.",
     "measured", "low", ["one more"], None, None, [], "research_brief.data_points (Thak case)", False),
    ("s56", "Thak",
     "In the village of Thak, in eastern Kumaon, a tigress had killed four people.",
     "In the village of Thak, in eastern Kumaon, a tigress had killed four people.",
     "measured", "low", ["four"], "broll", "Ink frame: a small hillside village at dusk, doors shut, no figures visible.", [],
     "research_brief.data_points (Thak septic-gunshot data point)", False),
    ("s57", "Tired",
     "Corbett was in his late fifties by then. Tired, by his own account, and increasingly certain each hunt should be his last.",
     "Corbett was in his late fifties by then. Tired, by his own account, and increasingly certain each hunt should be his last.",
     "slow", "low", ["tired"], None, None, [], "research_brief.data_points (Thak case)", False),
    ("s58", "She Kept Vanishing",
     "He tracked her for weeks. She kept vanishing.",
     "He tracked her for weeks. She kept vanishing.",
     "measured", "low", [], None, None, [], "research_brief.data_points (Thak case)", False),
    ("s59", "November 30, 1938",
     "On the 30th of November, 1938, in the last light of the day, he finally caught up to her — and killed her.",
     "On the thirtieth of November, nineteen thirty-eight, in the last light of the day, he finally caught up to her -- and killed her.",
     "slow", "medium", ["killed"], "overlay", "Ink frame: a rifle-holder's silhouette at dusk treeline, last light behind him.", [],
     "research_brief.data_points (Thak septic-gunshot data point)", False),
    ("s60", "His Final Hunt",
     "It was his final hunt.",
     "It was his final hunt.",
     "slow", "low", ["final"], None, None, [], "research_brief.data_points (Thak case)", False),
    ("s61", "Two Old Wounds",
     "The postmortem found two old gunshot wounds. One of them had turned septic.",
     "The postmortem found two old gunshot wounds. One of them had turned septic.",
     "slow", "low", ["septic"], "overlay", "White-ink-on-black inversion: detail of an old wound on a tiger's flank, examination table beneath.", [],
     "research_brief.data_points (Thak septic-gunshot data point)", False),
    ("s62", "The Same Story",
     "31 years after Champawat, on the far side of the same hills, the examination table told the same story.",
     "Thirty-one years after Champawat, on the far side of the same hills, the examination table told the same story.",
     "slow", "low", ["same"], None, None, [], "research_brief.angles_discovered (Five Tigers, Fifty Years, One Empire)", False),
    ("s63", "Not a Monster",
     "Not a monster. A wounded animal, run out of easier choices.",
     "Not a monster. A wounded animal, run out of easier choices.",
     "slow", "low", ["not"], None, None, [], "research_brief.research_summary", False),
    ("s64", "1944",
     "Corbett wrote the stories down. Man-Eaters of Kumaon was published in 1944, and it made him famous.",
     "Corbett wrote the stories down. Man-Eaters of Kumaon was published in nineteen forty-four, and it made him famous.",
     "measured", "low", ["1944"], "broll", "Ink frame: a worn hardcover book on a wooden table beside an oil lamp, title obscured.", [],
     "research_brief.landscape (Man-Eaters of Kumaon publication)", False),
    ("s65", "Remembered for the Reserve",
     "In India, though, he's remembered less for the rifle and more for the reserve — the one that still carries his name.",
     "In India, though, he's remembered less for the rifle and more for the reserve -- the one that still carries his name.",
     "measured", "low", [], None, None, [], "research_brief.data_points (Corbett National Park founding data point)", False),
    ("s66", "A Casualty First",
     "A hunter who spent his career proving that the monster was almost always a casualty first.",
     "A hunter who spent his career proving that the monster was almost always a casualty first.",
     "slow", "low", ["casualty"], None, None, [], "research_brief.research_summary", False),

    ("c5", "ACT FIVE title card", "ACT FIVE — WHAT'S LEFT", "Act Five. What's Left.",
     "measured", "low", [], "overlay", "ffmpeg drawtext act-break title card, plain ink-paper background; no image generation.",
     [], "act structure", True),

    ("s67", "Didn't Fix It",
     "None of this fixed the deeper problem.",
     "None of this fixed the deeper problem.",
     "measured", "low", [], None, None, [], "research_brief.data_points (tiger population collapse data point)", False),
    ("s68", "40,000 to Under 2,000",
     "Across the first seven decades of the twentieth century, India's tiger population collapsed — from an estimated 40,000 to 58,000 animals around 1900, to fewer than 2,000 by the early 1970s.",
     "Across the first seven decades of the twentieth century, India's tiger population collapsed -- from an estimated forty to fifty-eight thousand animals around nineteen hundred, to fewer than two thousand by the early nineteen seventies.",
     "measured", "low", ["collapsed"], "stat_card", "Overlay text: '~40,000-58,000 tigers (c.1900) -> under 2,000 (early 1970s)'", [],
     "research_brief.data_points (tiger population collapse data point)", False),
    ("s69", "The Same Forces",
     "Bounty hunting. Trophy shikar. Forest cleared for railways and farmland. The same forces that made the man-eaters kept eating away at everything else, too.",
     "Bounty hunting. Trophy shikar. Forest cleared for railways and farmland. The same forces that made the man-eaters kept eating away at everything else, too.",
     "measured", "medium", [], None, None, [], "research_brief.angles_discovered (The Colonial Machine That Made the Man-Eater)", False),
    ("s70", "No Corbett Moment",
     "Far to the east, in the Sundarbans, the story never really had a Jim Corbett moment — no single hunt that ended it.",
     "Far to the east, in the Sundarbans, the story never really had a Jim Corbett moment -- no single hunt that ended it.",
     "measured", "low", [], None, None, [], "research_brief.data_points (Sundarbans present-day data point)", False),
    ("s71", "Still There",
     "The delta's tigers are still there. So is the conflict.",
     "The delta's tigers are still there. So is the conflict.",
     "measured", "low", ["still"], "broll", "Ink frame: a present-day mangrove creek, boat prow entering frame from the right.", [],
     "research_brief.data_points (Sundarbans present-day data point)", False),
    ("s72", "100 to 120 a Year",
     "Today, the region still records somewhere around 100 to 120 deaths a year.",
     "Today, the region still records somewhere around a hundred to a hundred and twenty deaths a year.",
     "slow", "low", ["today"], "stat_card", "Overlay text: '~100-120 deaths a year, Sundarbans, present day'", [],
     "research_brief.data_points (tiger widows data point)", False),
    ("s73", "Never Makes It Into the Story",
     "And there's a cost that almost never makes it into the story.",
     "And there's a cost that almost never makes it into the story.",
     "slow", "low", [], None, None, [], "research_brief.audience_insights.pain_points", False),
    ("s74", "Bad Luck",
     "In the villages around the Sundarbans, women whose husbands were killed by tigers are still, in some communities, treated as bad luck.",
     "In the villages around the Sundarbans, women whose husbands were killed by tigers are still, in some communities, treated as bad luck.",
     "slow", "low", ["still"], "overlay", "Ink frame: a lone woman seated apart at the edge of a village gathering, others turned away.", [],
     "research_brief.data_points (tiger widows data point)", False),
    ("s75", "Swami Khejos",
     "Called, in Bengali, swami khejos. Husband-eaters. As if the loss were something they'd caused.",
     "Called, in Bengali, swami khejos. Husband-eaters. As if the loss were something they'd caused.",
     "slow", "low", ["husband-eaters"], None, None,
     [("swami khejos", "SHAH-mee kay-JOHSH")], "research_brief.data_points (tiger widows data point)", False),
    ("s76", "3,000 Women",
     "There are an estimated 3,000 of these women on the Indian side of the delta alone. A thousand more across the border in Bangladesh.",
     "There are an estimated three thousand of these women on the Indian side of the delta alone. A thousand more across the border in Bangladesh.",
     "slow", "low", ["3,000"], "stat_card", "Overlay text: '~3,000 tiger widows, India; ~1,000 more, Bangladesh'", [],
     "research_brief.data_points (tiger widows data point)", False),
    ("s77", "Still Paying",
     "They didn't do the killing. They're still paying for it.",
     "They didn't do the killing. They're still paying for it.",
     "slow", "low", ["still"], None, None, [], "research_brief.data_points (tiger widows data point)", False),
    ("s78", "A Century and a Half",
     "Every tiger in this story was examined after it died, and the table kept telling the same story, again and again, across a century and a half.",
     "Every tiger in this story was examined after it died, and the table kept telling the same story, again and again, across a century and a half.",
     "slow", "low", ["again and again"], "overlay", "Return to the cold-open examination-table frame (bookend).", [],
     "research_brief.research_summary", False),
    ("s79", "Not Hunger, Not Hatred",
     "Not hunger. Not hatred. An old wound, and a forest that kept getting smaller.",
     "Not hunger. Not hatred. An old wound, and a forest that kept getting smaller.",
     "slow", "low", ["not"], None, None, [], "research_brief.research_summary", False),
    ("s80", "Healed Into Policy",
     "The wound healed, eventually, into policy — a reserve here, a law there.",
     "The wound healed, eventually, into policy -- a reserve here, a law there.",
     "slow", "low", ["healed"], None, None, [], "research_brief.data_points (Corbett National Park founding data point)", False),
    ("s81", "Still Getting Smaller",
     "The forest is still getting smaller. And somewhere in the Sundarbans tonight, someone is still being blamed for what a wounded animal did.",
     "The forest is still getting smaller. And somewhere in the Sundarbans tonight, someone is still being blamed for what a wounded animal did.",
     "slow", "low", ["still", "blamed"], "animation", "Slow pull-back from the examination table frame to black; final fade.", [],
     "research_brief.data_points (tiger widows data point); research_brief.research_summary", False),
]

sections = []
t = 0.7  # opening offset, matches E01 convention
for (sid, label, text, provider_text, pace, energy, emphasis, etype, edesc, pronun, source_ref, is_card) in BEATS:
    if is_card:
        dur = CARD_DURATION
        gap = CARD_GAP
    else:
        words = len(text.split())
        dur = max(2.2, round(words / WPS, 2))
        gap = GAP
    start = round(t, 2)
    end = round(t + dur, 2)
    section = {
        "id": sid,
        "label": label,
        "text": text,
        "start_seconds": start,
        "end_seconds": end,
        "speaker_directions": edesc if is_card else f"{pace.capitalize()} pace, {energy} energy. {('Emphasize: ' + ', '.join(emphasis) + '.') if emphasis else ''}".strip(),
        "delivery_cues": {
            "pace": pace,
            "energy": energy,
            "emphasis_words": emphasis,
            "pause_before_seconds": 0 if start <= 1.0 else GAP,
            "pause_after_seconds": gap,
            "delivery_note": "Act-break title card: read the card text once, plainly, then hold silence into the next beat." if is_card else "Somber documentary register; the facts carry the weight, not the delivery.",
            "provider_text": provider_text,
        },
        "source_ref": source_ref,
    }
    if etype:
        section["enhancement_cues"] = [{"type": etype, "description": edesc, "timestamp_seconds": start + 0.1}]
    if pronun:
        section["pronunciation_guides"] = [{"word": w, "phonetic": p} for (w, p) in pronun]
    sections.append(section)
    t = end + gap

total_duration = round(sections[-1]["end_seconds"], 2)

script = {
    "version": "1.0",
    "title": "Ink & Testimony E02 — The Examination Table",
    "total_duration_seconds": total_duration,
    "voice_performance": {
        "performance_intent": "Somber documentary narrator, identical register to E01. Restrained and close-mic'd; the horror and the science are both in the facts, not the delivery. No melodrama, no upspeak, respectful to both the human victims and the animal.",
        "pacing_profile": "contemplative",
        "energy_curve": "Low and steady through Act One's policy/backdrop material; slight lift through the Champawat hunt (s25-s28) and the Chowgarh chase (s41-s47); flattest and quietest at the two postmortem reveals (s31-32, s61) and the coda (s78-s81)",
        "pause_policy": "0.55s hard gaps between narration beats, 0.8s after act-break cards (E01-validated grammar); no SSML -- multilingual_v2 does not support break tags",
        "sample_section_id": "s31",
        "provider_notes": {
            "elevenlabs": "voice S9GPGBaMND8XWwwzxQXp, eleven_multilingual_v2, stability 0.75, similarity 0.9, style 0.1, speed 1.0; audio tags NOT supported on this model -- provider_text must be plain prose; ALL numbers/dates/figures spelled out in provider_text per the E01 comma-numeral misnormalization fix (e.g. '1,600' was read as 'section')."
        },
    },
    "sections": sections,
    "metadata": {
        "concept": "C1 The Examination Table",
        "word_count": sum(len(s["text"].split()) for s in sections),
        "beat_count_narration": sum(1 for b in BEATS if not b[-1]),
        "act_break_cards": sum(1 for b in BEATS if b[-1]),
        "duration_check": f"Estimated {total_duration}s at contemplative pace ({WPS} wps) + beat/card gaps; target 600s (10 min); actual timings will be reconciled against real TTS clip durations at the assets/edit stage per the timing-assertion rule.",
        "style_anchors": "INK_STYLE / INK_STYLE_DARK blocks (verbatim from scripts/e01_generate_assets.py) + voice S9GPGBaMND8XWwwzxQXp (see proposal_packet.production_plan)",
        "act_structure": [
            {"act": 1, "title": "VERMIN", "sections": "s4-s18", "covers": "1822-1888 colonial bounty system, Forest Acts, Sundarbans land reclamation, colonial-era death toll"},
            {"act": 2, "title": "THE EXAMINATION", "sections": "s19-s34", "covers": "1890s-1907 Champawat Tigress, Corbett's first hunt, the canine-injury postmortem finding"},
            {"act": 3, "title": "WHAT MADE HER", "sections": "s35-s50", "covers": "modern scientific consensus on man-eating causation, then 1925-1930 Chowgarh tigers"},
            {"act": 4, "title": "THE LAST HUNT", "sections": "s51-s66", "covers": "1936 Corbett National Park founding, 1938 Thak man-eater and Corbett's final hunt"},
            {"act": 5, "title": "WHAT'S LEFT", "sections": "s67-s81", "covers": "1900s-1970s population collapse, present-day Sundarbans toll, tiger widows, closing thematic return to the examination table"},
        ],
    },
}

with open("projects/ink-testimony-e02/artifacts/script.json", "w") as f:
    json.dump(script, f, indent=2)

print("sections:", len(sections))
print("narration beats:", script["metadata"]["beat_count_narration"])
print("act cards:", script["metadata"]["act_break_cards"])
print("total_duration_seconds:", total_duration)
print("word_count:", script["metadata"]["word_count"])
